### PR TITLE
netlink: make peerid a nested attribute

### PR DESCRIPTION
**Pull request by hreinecke**
Convert 'PEERID' into a nested attribute to allow for several peerid attributes to be transmitted.

### CODE REVIEW

**Review by chucklever — COMMENTED** [review]
Don't you need to hand all of the identity material to the library and let it pass it to the server in a single handshake? If driving multiple gnutls_handshake() calls is really necessary, let's use a real C loop construct instead of "goto retry".

Note the comment at the top of netlink.h : That file is machine-generated. So you have to change the spec first and regenerate netlink.h from that. The spec is Documentation/netlink/specs/handshake.yaml in the kernel.

I'm told that nesting is no longer preferred for lists of attributes. Instead, we need to replace genlmsg_parse with nla_for_each_attr. I need to work out exactly what Jakub wants and the YAML schema allows. That's why I was not able to get multiple peer IDs into v5.

I'm guessing that multiple privkeys will go along with multiple x509 certificates.

**Comment by hreinecke** [comment]
> Don't you need to hand all of the identity material to the library and let it pass it to the server in a single handshake? If driving multiple gnutls_handshake() calls is really necessary, let's use a real C loop construct instead of "goto retry".
> 
Ideally, yes. And that's also what the TLS 1.3 spec says. Sadly neither OpenSSL nor gnutls implement more than one PSK per handshake. Hence the rather clunky way of calling into gnutls.
But just because the library doesn't implement it doesn't mean we have to follow the library; I'd rather follow the spec and work around deficiencies in the library.

> Note the comment at the top of netlink.h : That file is machine-generated. So you have to change the spec first and regenerate netlink.h from that. The spec is Documentation/netlink/specs/handshake.yaml in the kernel.
> 
Thought so. But note this is just a prototype, and I guess it _should_ work. I'm still about to test it out.

> I'm told that nesting is no longer preferred for lists of attributes. Instead, we need to replace genlmsg_parse with nla_for_each_attr. I need to work out exactly what Jakub wants and the YAML schema allows. That's why I was not able to get multiple peer IDs into v5.
> 
Yeah; I've figured as much. But the current parser has no way of dealing with attribute lists; we just have the parse array containing the value for that attribute type, which doesn't really align with having several attributes of the same type.
Must say I'm a bit suprised here; in the end, netlink messages are a stream of TLV tuples, so one _should_ be able to add more than one attribute with the same type to that message ...

> I'm guessing that multiple privkeys will go along with multiple x509 certificates.
I just made the least possible modifications for the x509 stuff; I'm not really into that and wanted to let you decide/figure out what to do here.

**Comment by chucklever** [comment]
> > Don't you need to hand all of the identity material to the library and let it pass it to the server in a single handshake? If driving multiple gnutls_handshake() calls is really necessary, let's use a real C loop construct instead of "goto retry".
> 
> Ideally, yes. And that's also what the TLS 1.3 spec says. Sadly neither OpenSSL nor gnutls implement more than one PSK per handshake.

That bears mentioning in a code comment (when multi-peer ID support makes it into tlshd).

> Hence the rather clunky way of calling into gnutls. But just because the library doesn't implement it doesn't mean we have to follow the library; I'd rather follow the spec and work around deficiencies in the library.

"I'd rather follow the [NVMe] spec..." just so we're clear.

If no TLS library implements multiple local identities, then I might question if the NVMe specification is complete or workable -- and further, whether any other implementation is going to bother supporting multiple local identities. Food for thought, not an objection.

> > I'm told that nesting is no longer preferred for lists of attributes. Instead, we need to replace genlmsg_parse with nla_for_each_attr. I need to work out exactly what Jakub wants and the YAML schema allows. That's why I was not able to get multiple peer IDs into v5.
> 
> Yeah; I've figured as much. But the current parser has no way of dealing with attribute lists; we just have the parse array containing the value for that attribute type, which doesn't really align with having several attributes of the same type.

That's precisely what nla_for_each_attr() is for. I would prefer to use genlmsg_parse() for the majority of attributes and leave the multiple ones insulated inside a nest. I've constructed a YAML update that uses nested-attributes and sent it to Jakub for his review and comment.

> > I'm guessing that multiple privkeys will go along with multiple x509 certificates.

> I just made the least possible modifications for the x509 stuff; I'm not really into that and wanted to let you decide/figure out what to do here.

I made some adjustments in my proposal. Let's see what Jakub says.

**Comment by hreinecke** [comment]
You misread my statement about the 'spec'. It's TLS 1.3 which specifies that the ClientHello contains a list of identities (cf [RFC 8446 Section 4.2.11](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.11) for PSK. So this really is gnutls not implementing this deliberately, and I'd rather follow the RFC than tying us to some userspace implementation. After all, someone might be willing to send a patch for the library ...

**Comment by chucklever** [comment]
> You misread my statement about the 'spec'. It's TLS 1.3 which specifies that the ClientHello contains a list of identities (cf [RFC 8446 Section 4.2.11](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.11) for PSK. So this really is gnutls not implementing this deliberately, and I'd rather follow the RFC than tying us to some userspace implementation.

The RFC specifies sending one ClientHello with multiple identities. What you implemented was sending multiple ClientHello messages each with a single identity. Not the same at all: the RFC's goal is to reduce round trips in cases like this.

> After all, someone might be willing to send a patch for the library ...

My concern is that no library implements this because there is an inherent problem with it. Standards are not perfect.

I encourage you to at least ask the GnuTLS folks why this support does not yet exist. It could be that no-one has found a need to use it, or it could be that there is a security reason it was not implemented. If you get an outright rejection for adding that capability, we shouldn't add it to the handshake netlink protocol.

Meanwhile I don't see a similar multi-identity capability for certificate-based authentication. It would make sense for the handshake protocol to handle zero or one cert/privkey pair or a list of PSKs (if it turns out there's no impediment to supporting the unimplemented parts of the PSK extension).

**Comment by chucklever** [comment]
Support for multiple peer IDs will appear in v7... but the netlink protocol might be a little different. I'm closing this PR, and we can make any needed fixes and adjustments in the netlink-v7 branch.

**Pull request closed without merging**
