### PR TITLE
Fixes to get PSK up and running

### PR DESCRIPTION
**Pull request by hreinecke**
Some fixes to get PSK up and running.
The 'timeout' attribute one needs to be taken with a grain of salt; it _looks_ reasonable, but then I haven't been able to test it as the 'assert()' from gnutls caused even more issues than a simple timeout.
But with these patches PSK is now working.

### CODE REVIEW

**Comment by hreinecke** [comment]
Oh, and forgot: this is against the 'netlink' branch; just in case github doesn't do is properly.

**Review by chucklever — CHANGES_REQUESTED** [review]
My initial reaction to this one is the keyring setting should be in /etc/tlshd.conf. We don't want folks to have to edit their systemd scripts. Or have I missed something?

**Comment by chucklever** [comment]
I can pull the first two of these into the main branch. The third needs some discussion, but should also go into the main branch. The remaining commits I will have to fold into the ongoing development work in the netlink branch, which is about to change radically because the kernel side has to use generic netlink.

**Review by chucklever — COMMENTED** [review]
No objection to having a more sensible timeout here, and looks like you plumbed it in correctly. I expected, actually, that the kernel consumers would implement their own "wake up if nothing happened after a few moments" logic so this kind of thing wouldn't be necessary. I'm wondering though if we really need to parametrize it here: maybe just picking one better timeout value for everyone would be OK?

**Comment by hreinecke** [comment]
> My initial reaction to this one is the keyring setting should be in /etc/tlshd.conf. We don't want folks to have to edit their systemd scripts. Or have I missed something?

No, you are correct; I had thought of adding it to the config file, but then got sidetracked. Will be doing so.

**Comment by hreinecke** [comment]
> I can pull the first two of these into the main branch. The third needs some discussion, but should also go into the main branch. The remaining commits I will have to fold into the ongoing development work in the netlink branch, which is about to change radically because the kernel side has to use generic netlink.
> 
Yeah, I've seen it. When you do, please be aware of the 'NLA_F_NESTED' flags. Don't want to waste another Monday tracking issues down :-)

> Plus, the netlink branch is a topic branch, so I feel free to alter its history, and will do so with prejudice.
> 
Fair enough.

> So FYI I'm probably going to reject this PR as whole, just for github.com book-keeping, and then apply the individual commits by hand in the places where they are appropriate.

Sure, do.

While at it: for NVMe-over-TCP TLS support we need at least gnutls-3.8.0, as that's the version where my patch to accept long identity strings went in. Maybe we should put a note somewhere.

**Comment by hreinecke** [comment]
> No objection to having a more sensible timeout here, and looks like you plumbed it in correctly. I expected, actually, that the kernel consumers would implement their own "wake up if nothing happened after a few moments" logic so this kind of thing wouldn't be necessary. I'm wondering though if we really need to parametrize it here: maybe just picking one better timeout value for everyone would be OK?

Weelll ... sadly, it's not that easy. The whole 'timeout' thingie got triggered with gnutls hitting an 'assert' for the psk identity. And then ... well, not sure _what_ happened, but the kernel side never got the 'accept' message, causing it to run into a timeout. And after the timeout the socket was done in.
I'm not sure _who_ caused that to happen; my initial hunch about a missing reference or the CLOEXEC flag didn't solve anything, so in the end I just accepted the fact and tore down the session completely.
So timeout handling definitely needs to be improved, but having a netlink attribute to signal the timeout value surely is a necessary first step here.

**Review by chucklever — COMMENTED** [review]
In my copy of libnl, nla_nest_start() does this already:

```
 /**
  * Start a new level of nested attributes.
  * @arg msg             Netlink message.
  * @arg attrtype        Attribute type of container.
  *
  * @return Pointer to container attribute.
  */
 struct nlattr *nla_nest_start(struct nl_msg *msg, int attrtype)
 {
         struct nlattr *start = (struct nlattr *) nlmsg_tail(msg->nm_nlh);
 
         if (nla_put(msg, NLA_F_NESTED | attrtype, 0, NULL) < 0)
                 return NULL;
 
         NL_DBG(2, "msg %p: attr <%p> %d: starting nesting\n",
                 msg, start, start->nla_type);
 
         return start;
 }
```

Which version of libnl are you using?

**Comment by chucklever** [comment]
> On Feb 14, 2023, at 12:49 PM, Hannes Reinecke ***@***.***> wrote:
> 
> While at it: for NVMe-over-TCP TLS support we need at least gnutls-3.8.0, as that's the version where my patch to accept long identity strings went in. Maybe we should put a note somewhere.

The minimum library version can be enforced in configure.ac. Maybe send a PR?

 The only issue there is whether github's CI infrastructure has 3.8 or better.

--
Chuck Lever

**Comment by chucklever** [comment]
On Feb 14, 2023, at 12:54 PM, Hannes Reinecke ***@***.******@***.***>> wrote:



No objection to having a more sensible timeout here, and looks like you plumbed it in correctly. I expected, actually, that the kernel consumers would implement their own "wake up if nothing happened after a few moments" logic so this kind of thing wouldn't be necessary. I'm wondering though if we really need to parametrize it here: maybe just picking one better timeout value for everyone would be OK?

Weelll ... sadly, it's not that easy. The whole 'timeout' thingie got triggered with gnutls hitting an 'assert' for the psk identity. And then ... well, not sure what happened, but the kernel side never got the 'accept' message, causing it to run into a timeout. And after the timeout the socket was done in.
I'm not sure who caused that to happen; my initial hunch about a missing reference or the CLOEXEC flag didn't solve anything, so in the end I just accepted the fact and tore down the session completely.

Tearing down the sock if an error occurs is the best choice no matter what. That will be documented a little better in the next version of the kernel code.


So timeout handling definitely needs to be improved, but having a netlink attribute to signal the timeout value surely is a necessary first step here.

I'm not convinced that parametrizing the timeout parameter is the very first step to address error handling problems. I'm not rejecting the idea, but maybe it might be premature.

I agree that the error unwind cases are tricky and hard to get right, and there's no guarantee at this point that the kernel code is entirely careful. I spent a lot of time for the next version of the kernel code trying to make that a little better. Plus I foresee some significant churn ahead as we address netdev's concerns.


--
Chuck Lever

**Comment by chucklever** [comment]
The netlink branch has been updated for v4 of the kernel netlink upcall. That version is radically different because we were asked to convert it to use generic netlink. Thus, this PR has been closed since it is now stale. Discussion of the work that has not been included in today's update can continue (related to default keyring support, etc).

Please note that I did not include the NLA_F_NESTED change: that appears to be a library version issue. It needs more root cause evaluation.

**Pull request closed without merging**
